export function generateAppealLetter(claim: Record<string, unknown>): string {
    const today = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
    });
    const denialCode = String(claim.denial_code ?? "Unknown");
    const denialDesc = String(claim.denial_description ?? "");

    const appealJustifications: Record<string, string> = {
        "CO-197":
            "The services provided were medically necessary and required urgent intervention. " +
            "Our clinical team attempted to obtain prior authorization but encountered delays " +
            "in the payer's authorization system. We respectfully request retroactive authorization " +
            "be granted based on the clinical urgency of the situation.",
        "CO-29":
            "We are appealing the denial based on timely filing. Enclosed please find proof of " +
            "our original submission including the electronic acknowledgment receipt confirming " +
            "the claim was submitted within the required filing period. The denial appears to be " +
            "in error and we request immediate reconsideration.",
        "CO-96":
            "The services rendered were medically necessary as documented in the attached clinical " +
            "notes. The treating physician has determined that this treatment was essential to the " +
            "patient's care and aligns with current evidence-based medical guidelines. We request " +
            "your clinical review team reconsider this determination.",
        "CO-22":
            "We are resubmitting this claim with updated coordination of benefits information. " +
            "Our records indicate this payer is the primary insurance for this patient. We have " +
            "attached updated insurance verification documentation for your review.",
    };

    const defaultJustification =
        `We are appealing the denial of this claim (Denial Code: ${denialCode}). ` +
        "The services provided were medically necessary and properly documented in the medical record. " +
        "We request your reconsideration based on the clinical documentation attached herein.";

    const justification = appealJustifications[denialCode] ?? defaultJustification;
    const charge = Number(claim.charge_amount ?? 0);

    return `
${today}

Appeals Department
${claim.payer ?? "Insurance Company"}
[Payer Address]
[City, State ZIP]

RE: FORMAL APPEAL - Claim Denial
    Patient: ${claim.patient_name ?? "N/A"}
    Date of Service: ${claim.dos ?? "N/A"}
    Claim ID: ${claim.claim_id ?? "N/A"}
    Denial Code: ${denialCode}
    Charge Amount: $${charge.toLocaleString("en-US", { minimumFractionDigits: 2 })}

Dear Appeals Department,

We are writing to formally appeal the denial of the above-referenced claim on behalf of our patient, ${claim.patient_name ?? "N/A"}.

CLAIM INFORMATION:
------------------
  Claim ID:           ${claim.claim_id ?? "N/A"}
  Patient Name:       ${claim.patient_name ?? "N/A"}
  Date of Service:    ${claim.dos ?? "N/A"}
  Provider:           ${claim.provider ?? "N/A"}
  Specialty:          ${claim.specialty ?? "N/A"}
  CPT Code(s):        ${claim.cpt ?? "N/A"}
  ICD-10 Code(s):     ${claim.icd ?? "N/A"}
  Billed Amount:      $${charge.toLocaleString("en-US", { minimumFractionDigits: 2 })}

DENIAL INFORMATION:
-------------------
  Denial Code:        ${denialCode}
  Denial Reason:      ${denialDesc || "See attached Explanation of Benefits"}

GROUNDS FOR APPEAL:
-------------------
${justification}

SUPPORTING DOCUMENTATION ENCLOSED:
1. Complete medical records for the date of service
2. Physician's letter of medical necessity
3. Relevant clinical guidelines supporting treatment
4. Prior authorization documentation (if applicable)
5. Original claim submission confirmation

We respectfully request that you review this appeal and reverse the denial determination. 
If additional information is required, please contact our billing department at your earliest 
convenience.

We expect a written response within 30 business days as required by state and federal regulations.

Sincerely,

Revenue Cycle Management Department
${claim.provider ?? "Medical Practice"}
Phone: (555) 123-4567
Fax: (555) 123-4568
Email: rcm@medicalpractice.com

Enclosures as listed above

---
This letter was generated by the RCM AR Workflow System on ${today}.
`.trim();
}
